In [1]:
import numpy as np


In [3]:
# Tạo mảng 3 phần tử
a = np.array([1,2,3])


In [5]:
# In mảng
print(a)

[1 2 3]


In [7]:
# In ra phần tử ở vị trí thứ 2
element = a[1]
print(element)

2


In [9]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# In một phần tử ở hàng 2 phần tử thứ 3
element = matrix[1, 2]
print(element)

6


In [13]:
# Tạo mảng 5 là số 0
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [15]:
# Tạo mảng 5 là số 1
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [17]:
# Tạo mảng rỗng kích thước 5
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [19]:
# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [21]:
# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [27]:
# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

array([1, 1, 1, 1, 1], dtype=int64)

In [29]:
# Thêm, xóa, sắp xếp mảng

In [31]:
# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

[3 1 2 4 5]


In [33]:
# Sắp xếp
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [35]:
# Sắp xếp ngược
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [37]:
# Thêm phần tử vào mảng
arr = np.append(arr, 100)
print(arr)

[  5   4   3   2   1 100]


In [39]:
# Xóa đi một ví trí số thư 4 trong mảng
arr = np.delete(arr, 3)
print(arr)

[  5   4   3   1 100]


In [41]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 2, 1],
                [4, 6, 8],
                [9, 7, 5]])

In [43]:
sap_xep_theo_hang = np.sort(arr, axis=1) # tăng dần
print(sap_xep_theo_hang)

[[1 2 3]
 [4 6 8]
 [5 7 9]]


In [45]:
sap_xep_theo_cot = np.sort(arr, axis=0) # tăng dần
print(sap_xep_theo_cot)

[[3 2 1]
 [4 6 5]
 [9 7 8]]


In [47]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

In [49]:
sap_xep_theo_hang = -np.sort(-arr, axis=1) # giảm dần
print(sap_xep_theo_hang)

[[3 2 1]
 [8 6 4]
 [9 7 5]]


In [51]:
sap_xep_theo_cot = -np.sort(-arr, axis=0) # giảm dần
print(sap_xep_theo_cot)


[[9 7 8]
 [4 6 5]
 [3 1 2]]


In [53]:
# Tạo một mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [55]:
# Sử dụng các thuộc tính như ndim size shape
so_chieu = arr.ndim  # Số chiều 
kich_thuoc = arr.size  # Kích thước 
hinh_dang = arr.shape  # Hình dạng 

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [59]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float) # ép kiểu
print(arr_float)

[1. 2. 3. 4. 5.]


In [61]:
# Thay đổi hình dạng của mảng
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [63]:
reshaped_arr = reshaped_arr.flatten() # Chuyển lại mảng 1 h=chièu
print(reshaped_arr)

[1 2 3 4 5 6]


In [65]:
# Cắt lát mảng
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  # cắt phần từ cuối
print(sub_arr)

sub_arr = arr[-2:]  # 4 5
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [67]:
# Chuyển vị mảng
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [69]:
# Nối 2 mảng lại vs nhau
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
